// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_admin_profiles_delete_email_ from "./routes/(admin)/profiles/delete/[email].tsx";
import * as $_admin_profiles_edit_email_ from "./routes/(admin)/profiles/edit/[email].tsx";
import * as $_admin_profiles_index from "./routes/(admin)/profiles/index.tsx";
import * as $_admin_profiles_new from "./routes/(admin)/profiles/new.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_appointments_id_delete from "./routes/api/appointments/[id]/delete.ts";
import * as $api_appointments_id_update from "./routes/api/appointments/[id]/update.ts";
import * as $api_appointments_create from "./routes/api/appointments/create.ts";
import * as $api_appointments_index from "./routes/api/appointments/index.ts";
import * as $api_auth_check from "./routes/api/auth/check.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_profiles_id_delete from "./routes/api/profiles/[id]/delete.ts";
import * as $api_profiles_id_update from "./routes/api/profiles/[id]/update.ts";
import * as $api_profiles_create from "./routes/api/profiles/create.ts";
import * as $api_profiles_index from "./routes/api/profiles/index.ts";
import * as $appointments_id_ from "./routes/appointments/[id].tsx";
import * as $appointments_index from "./routes/appointments/index.tsx";
import * as $appointments_new from "./routes/appointments/new.tsx";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $dashboard_profiles from "./routes/dashboard/profiles.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $AppointmentCalendar from "./islands/AppointmentCalendar.tsx";
import * as $AppointmentForm from "./islands/AppointmentForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DashboardStats from "./islands/DashboardStats.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(admin)/profiles/delete/[email].tsx":
      $_admin_profiles_delete_email_,
    "./routes/(admin)/profiles/edit/[email].tsx": $_admin_profiles_edit_email_,
    "./routes/(admin)/profiles/index.tsx": $_admin_profiles_index,
    "./routes/(admin)/profiles/new.tsx": $_admin_profiles_new,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/appointments/[id]/delete.ts": $api_appointments_id_delete,
    "./routes/api/appointments/[id]/update.ts": $api_appointments_id_update,
    "./routes/api/appointments/create.ts": $api_appointments_create,
    "./routes/api/appointments/index.ts": $api_appointments_index,
    "./routes/api/auth/check.ts": $api_auth_check,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/profiles/[id]/delete.ts": $api_profiles_id_delete,
    "./routes/api/profiles/[id]/update.ts": $api_profiles_id_update,
    "./routes/api/profiles/create.ts": $api_profiles_create,
    "./routes/api/profiles/index.ts": $api_profiles_index,
    "./routes/appointments/[id].tsx": $appointments_id_,
    "./routes/appointments/index.tsx": $appointments_index,
    "./routes/appointments/new.tsx": $appointments_new,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/dashboard/profiles.tsx": $dashboard_profiles,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/AppointmentCalendar.tsx": $AppointmentCalendar,
    "./islands/AppointmentForm.tsx": $AppointmentForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/DashboardStats.tsx": $DashboardStats,
    "./islands/Header.tsx": $Header,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
